authtoken: 1SfXtgDwi90Hk73hFaAXUSYl3q7_DGt7aHvZbfRUWBZG7p8E
json_resolver_url: ""
dns_resolver_ips: []
console_ui: false
log:
log_format: term
region: us
web_addr: false
tunnels:
  ssh:
    proto: tcp
    addr: 22
    inspect: false
