authtoken: 1gOH50HUSlthsui4SzrVPqFupv5_5k5uMxHqNXWBiudtocoKj
json_resolver_url: ""
dns_resolver_ips: []
console_ui: false
log:
log_format: term
region: us
web_addr: false
tunnels:
  ssh:
    proto: tcp
    addr: 22
    inspect: false